import 'bootstrap/dist/css/bootstrap.css'
import Head from 'next/head';
import { createGlobalStyle } from "styled-components";

const GlobalStyle = createGlobalStyle`
  html,
  body {
    padding: 0;
    margin: 0;
    font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen,
      Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif;
  }

  a {
    color: inherit;
    text-decoration: none;

    &:hover{
      text-decoration: underline;
    }
  }

  * {
    box-sizing: border-box;
  }
`;


function MyApp({ Component, pageProps }) {
  return <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <GlobalStyle />
    <Component {...pageProps} />
  </>

}

export default MyApp;
