import 'bootstrap/dist/css/bootstrap.css'
import Head from 'next/head';

import "@fortawesome/fontawesome-svg-core/styles.css"; // import Font Awesome CSS
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false; // Tell Font Awesome to skip adding the CSS automatically since it's being imported above

import { Provider } from 'react-redux';
import store from '../redux/store';
import GlobalStyle from '../styles/global';
import { useEffect, useState } from 'react';
import { initApi } from '../api';

function MyApp({ Component, pageProps }) {
  const [init, setInit] = useState(false);

  useEffect(() => {
    initApi();
    setInit(true);
  }, [])


  return <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <GlobalStyle />
    {init && <Provider store={store}>
      <Component {...pageProps} />
    </Provider>}
  </>
}

export default MyApp;
